[language-server.tinymist.config]

command = "tinymist"
config = { preview.background.enabled = true, preview.background.args = ["--data-plane-host=127.0.0.1:23635", "--invert-colors=never", "--open"], exportPdf = "onType" }
typstExtraArgs = ["main.typ"]
